-- MCM 실제 상품 50건을 카탈로그에 추가하는 증분이다(id 19-68).
--
-- 기존 18건은 건드리지 않는다 — id 1-10은 가방·지갑(06-real-products.sql이 일부를 실제 상품으로 교체함),
-- id 11-18은 코디용 의류다. 프론트 이미지 규약이 /products/{id}.webp라 id를 바꾸면 전부 다시 매핑해야 한다.
--
-- 함정 1: color는 '코냑' 또는 '블랙'만 쓴다. 추천이 취향 답변과 이 문자열을 그대로 비교해 점수를 준다.
-- 함정 2: style_tags는 캐주얼·미니멀·스트릿·클래식·러블리·포멀 여섯 중에서만 쓴다. 추천 근거 문구에 값이 그대로 박힌다.
--         이 태그는 MCM이 붙인 것이 아니라 상품명과 라인 성격을 근거로 우리가 판단해 붙인 것이다.
-- 함정 3: price는 미국 정가(USD)를 환율 1429로 환산한 값이며 국내 판매가가 아니다.
-- 함정 4: 06-real-products.sql이 id 1,2,3,5에 쓴 SKU 4건(MMRGATA07BK001, MWSGSTA02CO001,
--         MXADATA08CO001, MYSGSTA01BK001)은 중복을 피해 이 50건에서 제외했다.
-- 함정 5: 일부 official_url에 '®' 문자가 들어 있다. 그대로 두면 열린다 — 인코딩하지 말 것.
--         적용할 때 --default-character-set=utf8mb4를 빼면 한글과 함께 깨진다.
--
-- 함정 6: **추천과 스타일링 응답에 image_url이 없다**(`RecommendService.ProductView`에 필드 자체가 없음).
--         여기 넣은 공식 이미지 URL은 DB에만 있고 화면까지 가지 않는다. 프론트가 `/products/{id}.webp`
--         규약을 쓰는 한 19-68은 이미지가 빈다. 살리려면 API에 `imageUrl`을 노출하는 별도 작업이 필요하다.
-- 함정 7: **적용하면 기존 기본 추천 결과가 바뀐다.** 취향 없이 기본 예산(50-150만)으로 부를 때
--         관계 넷 중 셋에서 1순위 밖 순위가 새 상품으로 밀린다(2026-08-12 codex 정적 분석).
--         과거에 저장된 추천 스냅샷과 그 추천으로 보낸 선물은 재계산하지 않으므로 그대로 유지된다.
--
-- 적용 순서
--   신규 인스턴스: 01-schema → 03-deploy-seed → 06-real-products → 07-product-catalog.
--                  **04-clothing-increment는 실행하지 않는다** — 03에 id 11-18이 이미 들어 있어 중복 키로 실패한다.
--   기존 운영 DB(현재 상품 18건): 이 파일만 적용한다.
--
-- 적용 전 확인 둘. 하나라도 0이 아니면 실행하지 말 것
--   SELECT COUNT(*) FROM product WHERE id BETWEEN 19 AND 68;
--   SELECT COUNT(*) FROM product WHERE demo_serial LIKE 'MX2024K%' OR demo_serial LIKE 'MX2024L%'
--     OR demo_serial LIKE 'MX2024M%' OR demo_serial LIKE 'MX2024N%' OR demo_serial LIKE 'MX2024P%';
--
-- 롤백 — **"언제든 되돌릴 수 있다"가 아니다.**
--   recommendation_result·gift·owned_product가 product를 FK로 참조하고 기본 동작이 RESTRICT라,
--   사용자가 새 상품을 한 번이라도 추천받으면 그 행 때문에 DELETE가 실패한다. 되돌리기 전에 참조부터 센다.
--   SELECT (SELECT COUNT(*) FROM recommendation_result WHERE product_id BETWEEN 19 AND 68)
--        + (SELECT COUNT(*) FROM gift WHERE product_id BETWEEN 19 AND 68)
--        + (SELECT COUNT(*) FROM owned_product WHERE product_id BETWEEN 19 AND 68) AS refs;
--   refs가 0일 때만: DELETE FROM product WHERE id BETWEEN 19 AND 68;
--   0이 아니면 지우지 말 것 — 사용자 데이터가 끊긴다. 그때는 롤포워드로 해결한다.
--
-- 선정 근거와 분포표: .plans/_quick/product-catalog-선정근거.md
--
-- 적용(비밀번호는 컨테이너 env로만 넘긴다. 셸 인자에 값을 박지 말 것):
--   docker compose exec -T mysql sh -c 'mysql --default-character-set=utf8mb4 -uroot -p"$MYSQL_ROOT_PASSWORD" mcmory_java' < 07-product-catalog.sql

SET NAMES utf8mb4;

INSERT INTO product (id, name, category, color, price, image_url, official_url, style_tags, demo_serial) VALUES
  (19, 'Stark Packable Backpack in Monogram Nylon', '가방', '블랙', 970000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMKGSVE09BK001_01/MMKGSVE09BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/stark-packable-backpack-in-monogram-nylon/MMKGSVE09BK001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024K001'),
  (20, 'Aren Sling in Visetos', '가방', '블랙', 1190000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMLGSTA03BK001_01/MMLGSTA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-sling-in-visetos/MMLGSTA03BK001.html', JSON_ARRAY('미니멀','캐주얼'), 'MX2024K002'),
  (21, 'Aren Drawstring Backpack in ECONYL and Leather', '가방', '블랙', 1260000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWKFATA04BK001_01/MWKFATA04BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-drawstring-backpack-in-econyl®-and-leather/MWKFATA04BK001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024K003'),
  (22, 'Aren Nova Backpack in Monogram ECONYL', '가방', '블랙', 1400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMKGATA02BK001_01/MMKGATA02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-nova-backpack-in-monogram-econyl®/MMKGATA02BK001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024K004'),
  (23, 'Pina Drawstring Backpack in Studded Calfskin', '가방', '블랙', 2400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWKGATA01BK001_01/MWKGATA01BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/pina-drawstring-backpack-in-studded-calfskin/MWKGATA01BK001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024K005'),
  (24, 'Aren Sling Bag in Visetos', '가방', '코냑', 1110000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMLGATA04CO001_01/MMLGATA04CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-sling-bag-in-visetos/MMLGATA04CO001.html', JSON_ARRAY('미니멀','캐주얼'), 'MX2024K006'),
  (25, 'Aren Sling in Visetos', '가방', '코냑', 1330000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMLFSTA01CO001_01/MMLFSTA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-sling-in-visetos/MMLFSTA01CO001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024K007'),
  (26, 'Stark Side Studs Backpack in Visetos', '가방', '코냑', 1760000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMKEAVE15CO001_01/MMKEAVE15CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/stark-side-studs-backpack-in-visetos/MMKEAVE15CO001.html', JSON_ARRAY('스트릿','캐주얼'), 'MX2024K008'),
  (27, 'MCM x We The Best Stark Backpack in Visetos', '가방', '코냑', 2070000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMKGAVE09CO001_01/MMKGAVE09CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/mcm-x-we-the-best-stark-backpack-in-visetos/MMKGAVE09CO001.html', JSON_ARRAY('스트릿','캐주얼'), 'MX2024K009'),
  (28, 'Aren Multi-Backpack in Visetos', '가방', '코냑', 2290000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMKEATA02CO001_01/MMKEATA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/bags/backpacks/aren-multi-backpack-in-visetos/MMKEATA02CO001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024K010'),
  (29, 'Aren East West Shoulder Bag in Visetos', '가방', '블랙', 1070000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWSGATA01BK001_01/MWSGATA01BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/aren-east-west-shoulder-bag-in-visetos/MWSGATA01BK001.html', JSON_ARRAY('미니멀','클래식'), 'MX2024L011'),
  (30, 'Aren Vanity Case in Visetos Leather Mix', '가방', '블랙', 1190000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWRGATA05BK001_01/MWRGATA05BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/aren-vanity-case-in-visetos-leather-mix/MWRGATA05BK001.html', JSON_ARRAY('러블리','캐주얼'), 'MX2024L012'),
  (31, 'Aren Duo Hobo in Visetos', '가방', '블랙', 1400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWHGSTA04BK001_01/MWHGSTA04BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/aren-duo-hobo-in-visetos/MWHGSTA04BK001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024L013'),
  (32, 'Ella Boston Bag in Visetos', '가방', '블랙', 1400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWBFAEA03BK001_01/MWBFAEA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/ella-boston-bag-in-visetos/MWBFAEA03BK001.html', JSON_ARRAY('클래식','포멀'), 'MX2024L014'),
  (33, 'Pina Tambourine Bag in Studded Calfskin', '가방', '블랙', 2210000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWRGAOB03BK001_01/MWRGAOB03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/pina-tambourine-bag-in-studded-calfskin/MWRGAOB03BK001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024L015'),
  (34, 'Aren Vanity Case in Visetos Leather Mix', '가방', '코냑', 970000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWRGSTA02CO001_01/MWRGSTA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/aren-vanity-case-in-visetos-leather-mix/MWRGSTA02CO001.html', JSON_ARRAY('러블리','캐주얼'), 'MX2024L016'),
  (35, 'Rockstar Vanity Case in Visetos Original', '가방', '코냑', 990000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWRAAVI01CO001_01/MWRAAVI01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/rockstar-vanity-case-in-visetos-original/MWRAAVI01CO001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024L017'),
  (36, 'Tracy Shoulder Bag in Visetos', '가방', '코냑', 1400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWSGAXT03CO001_01/MWSGAXT03CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/tracy-shoulder-bag-in-visetos/MWSGAXT03CO001.html', JSON_ARRAY('클래식','미니멀'), 'MX2024L018'),
  (37, 'Dessau Drawstring Bag in Visetos', '가방', '코냑', 1540000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWDGSDU03CO001_01/MWDGSDU03CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/dessau-drawstring-bag-in-visetos/MWDGSDU03CO001.html', JSON_ARRAY('캐주얼','클래식'), 'MX2024L019'),
  (38, 'Aren Zip Hobo in Visetos', '가방', '코냑', 1790000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMHGATA01CO001_01/MMHGATA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/shoulder-crossbody-bags/aren-zip-hobo-in-visetos/MMHGATA01CO001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024L020'),
  (39, 'Aren Nova Tote in ECONYL', '가방', '블랙', 970000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMTGATA03BK001_01/MMTGATA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/aren-nova-tote-in-econyl®/MMTGATA03BK001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024M021'),
  (40, 'New Liz Shopper in Visetos', '가방', '블랙', 1110000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWPGSLR05BK001_01/MWPGSLR05BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/new-liz-shopper-in-visetos/MWPGSLR05BK001.html', JSON_ARRAY('클래식','포멀'), 'MX2024M022'),
  (41, 'Aren School Bag Tote in Visetos', '가방', '블랙', 1190000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWTGSTA03BK001_01/MWTGSTA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/aren-school-bag-tote-in-visetos/MWTGSTA03BK001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024M023'),
  (42, 'Reversible Liz Shopper in Visetos', '가방', '블랙', 1260000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWPCSVI02BK001_01/MWPCSVI02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/reversible-liz-shopper-in-visetos/MWPCSVI02BK001.html', JSON_ARRAY('클래식','캐주얼'), 'MX2024M024'),
  (43, 'New Liz Shopper in Embossed Monogram Leather', '가방', '블랙', 1400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWPGALR02BK001_01/MWPGALR02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/new-liz-shopper-in-embossed-monogram-leather/MWPGALR02BK001.html', JSON_ARRAY('포멀','미니멀'), 'MX2024M025'),
  (44, 'Dia Shopper in Calfskin Leather', '가방', '블랙', 1970000, 'https://images.mcmworldwide.com/i/mcmworldwide/MMPGSDC02BK001_01/MMPGSDC02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/dia-shopper-in-calfskin-leather/MMPGSDC02BK001.html', JSON_ARRAY('미니멀','포멀'), 'MX2024M026'),
  (45, 'Aren Continental Wallet in Visetos', '지갑', '코냑', 790000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLFATA04CO001_01/MYLFATA04CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-continental-wallet-in-visetos/MYLFATA04CO001.html', JSON_ARRAY('포멀','클래식'), 'MX2024M027'),
  (46, 'Toni Top-Zip Shopper in Disco Visetos', '가방', '코냑', 1210000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWPGAMT01CO001_01/MWPGAMT01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/toni-top-zip-shopper-in-disco-visetos/MWPGAMT01CO001.html', JSON_ARRAY('스트릿','캐주얼'), 'MX2024M028'),
  (47, 'Aren School Bag Tote in Visetos', '가방', '코냑', 1330000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWTFATA02CO001_01/MWTFATA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/aren-school-bag-tote-in-visetos/MWTFATA02CO001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024M029'),
  (48, 'Pina Studded Tote in Visetos', '가방', '코냑', 1830000, 'https://images.mcmworldwide.com/i/mcmworldwide/MWTGATA01CO001_01/MWTGATA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/bags/totes-shoppers/pina-studded-tote-in-visetos/MWTGATA01CO001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024M030'),
  (49, 'Pina Wallet in Studded Calfskin', '지갑', '블랙', 690000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYSGAAF01BK001_01/MYSGAAF01BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/pina-wallet-in-studded-calfskin/MYSGAAF01BK001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024N031'),
  (50, 'Aren Chain Wallet in Embossed Monogram Leather', '지갑', '블랙', 760000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLGSTA02BK001_01/MYLGSTA02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-chain-wallet-in-embossed-monogram-leather/MYLGSTA02BK001.html', JSON_ARRAY('미니멀','러블리'), 'MX2024N032'),
  (51, 'Aren Crossbody Wallet in Visetos', '지갑', '블랙', 900000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXZGSTA01BK001_01/MXZGSTA01BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-crossbody-wallet-in-visetos/MXZGSTA01BK001.html', JSON_ARRAY('캐주얼','미니멀'), 'MX2024N033'),
  (52, 'Pina Crossbody Wallet in Studded Calfskin', '지갑', '블랙', 970000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLGATA03BK001_01/MYLGATA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/pina-crossbody-wallet-in-studded-calfskin/MYLGATA03BK001.html', JSON_ARRAY('스트릿','캐주얼'), 'MX2024N034'),
  (53, 'Aren Crossbody Wallet in Embossed Monogram Leather', '지갑', '블랙', 1010000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXZGATA04BK001_01/MXZGATA04BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-crossbody-wallet-in-embossed-monogram-leather/MXZGATA04BK001.html', JSON_ARRAY('미니멀','포멀'), 'MX2024N035'),
  (54, 'Bifold Zip Card Wallet in Visetos Original', '지갑', '코냑', 470000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXSFATA02CO001_01/MXSFATA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/bifold-zip-card-wallet-in-visetos-original/MXSFATA02CO001.html', JSON_ARRAY('클래식','미니멀'), 'MX2024N036'),
  (55, 'Zip Wallet in Visetos Original', '지갑', '코냑', 540000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLAAVI03CO001_01/MYLAAVI03CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/zip-wallet-in-visetos-original/MYLAAVI03CO001.html', JSON_ARRAY('클래식'), 'MX2024N037'),
  (56, 'Aren Trifold Wallet in Visetos', '지갑', '코냑', 540000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYSFSTA02CO001_01/MYSFSTA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-trifold-wallet-in-visetos/MYSFSTA02CO001.html', JSON_ARRAY('미니멀','캐주얼'), 'MX2024N038'),
  (57, 'Tracy Chain Card Wallet in Visetos', '지갑', '코냑', 590000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYAESXT02CO001_01/MYAESXT02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/tracy-chain-card-wallet-in-visetos/MYAESXT02CO001.html', JSON_ARRAY('러블리','캐주얼'), 'MX2024N039'),
  (58, 'Aren Zip Wallet in Disco Visetos', '지갑', '코냑', 590000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLGATA02CO001_01/MYLGATA02CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-zip-wallet-in-disco-visetos/MYLGATA02CO001.html', JSON_ARRAY('스트릿','러블리'), 'MX2024N040'),
  (59, 'Pina Wallet in Studded Visetos', '지갑', '코냑', 640000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYSGATA01CO001_01/MYSGATA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/pina-wallet-in-studded-visetos/MYSGATA01CO001.html', JSON_ARRAY('스트릿','클래식'), 'MX2024P041'),
  (60, 'Aren Zip Around Wallet in Visetos', '지갑', '코냑', 790000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYLFSTA01CO001_01/MYLFSTA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-zip-around-wallet-in-visetos/MYLFSTA01CO001.html', JSON_ARRAY('클래식','포멀'), 'MX2024P042'),
  (61, 'Aren Card Case in Visetos', '가죽 소품', '블랙', 300000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXADATA08BK001_01/MXADATA08BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-card-case-in-visetos/MXADATA08BK001.html', JSON_ARRAY('미니멀'), 'MX2024P043'),
  (62, 'Card Case in Visetos Original', '가죽 소품', '블랙', 300000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXAAAVI03BK001_01/MXAAAVI03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/card-case-in-visetos-original/MXAAAVI03BK001.html', JSON_ARRAY('클래식'), 'MX2024P044'),
  (63, 'Aren Card Case in Embossed Monogram Leather', '가죽 소품', '블랙', 330000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYAESTA03BK001_01/MYAESTA03BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-card-case-in-embossed-monogram-leather/MYAESTA03BK001.html', JSON_ARRAY('미니멀','클래식'), 'MX2024P045'),
  (64, 'Lanyard ID Card Holder in Embossed Monogram Leather', '가죽 소품', '블랙', 400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXZGATA02BK001_01/MXZGATA02BK001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/lanyard-id-card-holder-in-embossed-monogram-leather/MXZGATA02BK001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024P046'),
  (65, 'Lanyard ID Card Holder in Visetos', '가죽 소품', '코냑', 330000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXZGATA01CO001_01/MXZGATA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/lanyard-id-card-holder-in-visetos/MXZGATA01CO001.html', JSON_ARRAY('캐주얼','스트릿'), 'MX2024P047'),
  (66, 'Key Pouch in Visetos Original', '가죽 소품', '코냑', 360000, 'https://images.mcmworldwide.com/i/mcmworldwide/MXKCSVI01CO001_01/MXKCSVI01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/key-pouch-in-visetos-original/MXKCSVI01CO001.html', JSON_ARRAY('클래식','러블리'), 'MX2024P048'),
  (67, 'Aren Card Pouch in Visetos', '가죽 소품', '코냑', 400000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYAFATA01CO001_01/MYAFATA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-card-pouch-in-visetos/MYAFATA01CO001.html', JSON_ARRAY('미니멀','러블리'), 'MX2024P049'),
  (68, 'Aren Card Pouch in Visetos', '가죽 소품', '코냑', 470000, 'https://images.mcmworldwide.com/i/mcmworldwide/MYAGSTA01CO001_01/MYAGSTA01CO001?$large$&fmt=auto&qlt=default', 'https://us.mcmworldwide.com/en_US/women/wallets-small-leather-goods/all-wallets/aren-card-pouch-in-visetos/MYAGSTA01CO001.html', JSON_ARRAY('미니멀','러블리'), 'MX2024P050');
